// src/components/TechDrawer/index.tsx
import { Button, Drawer } from "antd";
import { FC, memo, useCallback } from "react";
import { TechDataType } from "../../types/static";
import './index.less'
interface TechDrawerProps{
    techData: TechDataType;
    setVisible: (boolean:boolean) => void;
    visible:boolean;
    onChooseList:(type:'tools'|'webgl'|'frame'|'list',index:number)=>void
}
const TechDrawer:FC<TechDrawerProps> =memo(({techData,visible,setVisible,onChooseList})=>{
const {tools,webgl,frame,list}=techData
const onClose=useCallback(()=>{
    setVisible(false)
},[setVisible])
    return <>
    <Drawer
    title="选择你的技能"
    width="720"
    visible={visible}
    bodyStyle={{paddingBottom: '80px' }}
    footerStyle={{ textAlign: 'right' }}
    onClose={onClose}
  >
    <div className="chooseList">
        {tools.map((v,i)=> <div className="btn">
        <Button
        type={v.select ? 'primary' : 'default'}
        onClick={()=>onChooseList('tools',i)}
        >{ v.name}</Button>
      </div>)
      }
      {webgl.map((v,i)=> <div className="btn">
        <Button
        type={v.select ? 'primary' : 'default'}
        onClick={()=>onChooseList('webgl',i)}
        >{ v.name}</Button>
      </div>)
      }
      {frame.map((v,i)=> <div className="btn">
        <Button
        type={v.select ? 'primary' : 'default'}
        onClick={()=>onChooseList('frame',i)}
        >{ v.name}</Button>
      </div>)
      }
       {list.map((v,i)=> <div className="btn">
        <Button
        type={v.select ? 'primary' : 'default'}
        onClick={()=>onChooseList('list',i)}
        >{ v.name}</Button>
      </div>)
      }
    </div>
  </Drawer>
    </>
})
export default TechDrawer

// src/components/TechDrawer.vue
<template>
  <a-drawer
    title="选择你的技能"
    :width="720"
    :visible="props.visible"
    :body-style="{ paddingBottom: '80px' }"
    :footer-style="{ textAlign: 'right' }"
    @close="onClose"
  >
    <div class="chooseList">
      <div class="btn" v-for="item in props.techData.tools">
        <a-button
          :type="item.select ? 'primary' : 'default'"
          @click="item.select = !item.select"
          >{{ item.name }}</a-button
        >
      </div>
      <div class="btn" v-for="item in props.techData.webgl">
        <a-button
          :type="item.select ? 'primary' : 'default'"
          @click="item.select = !item.select"
          >{{ item.name }}</a-button
        >
      </div>

      <div class="btn" v-for="item in props.techData.frame">
        <a-button
          :type="item.select ? 'primary' : 'default'"
          @click="item.select = !item.select"
          >{{ item.name }}</a-button
        >
      </div>
      <div class="btn" v-for="item in props.techData.list">
        <a-button
          :type="item.select ? 'primary' : 'default'"
          @click="item.select = !item.select"
          >{{ item.name }}</a-button
        >
      </div>
    </div>
  </a-drawer>
</template>

<script setup>
let props = defineProps(["techData", "visible"]);
let emit = defineEmits(["setVisible"]);

const rules = {
  name: [{ required: true, message: "Please enter user name" }],
  url: [{ required: true, message: "please enter url" }],
  owner: [{ required: true, message: "Please select an owner" }],
  type: [{ required: true, message: "Please choose the type" }],
  approver: [{ required: true, message: "Please choose the approver" }],
  dateTime: [
    { required: true, message: "Please choose the dateTime", type: "object" },
  ],
  description: [{ required: true, message: "Please enter url description" }],
};

function onClose() {
  emit("setVisible", false);
}
</script>

<style>
.chooseList {
  display: flex;
  flex-wrap: wrap;
}
.btn {
  padding: 5px 10px;
}
</style>
